version: 2.1

executors:
  node-10153:
    docker:
      - image: regviz/node-xcb
    working_directory: ~/repo
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/root/gcloud-service-key.json"

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  test:
    executor: node-10153
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install --pure-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}
      - run:
          name: Setup GCP
          command: echo $GCLOUD_SERVICE_KEY | base64 -d > /root/gcloud-service-key.json
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Unit Test
          command: yarn test:unit
      - codecov/upload:
          file: coverage/*.json
      - run:
          name: Screenshot
          command: |
            yarn storybook &
            yarn screenshot
      - store_artifacts:
          path: ./__screenshots__
          destination: screenshots
      - run:
          name: Visual Test
          command: yarn test:visual

  deploy:
    executor: node-10153
    parameters:
      env:
        type: enum
        enum: ['PRODUCTION']
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "functions/package.json" }}
      - run:
          name: Install dependencies
          command: yarn install --pure-lockfile
      - run:
          name: Install dependencies for cloud functions
          command: cd functions && npm install
      - run: npm install -D firebase-tools
      - save_cache:
          paths:
            - node_modules
            - functions/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "functions/package.json" }}
      - run:
          name: Decode Environment Variables
          command: echo $<< parameters.env >>_DOT_ENV | base64 -d > .env
      - run:
          name: Build
          command: yarn build
      - run:
          name: Deploy
          command: node_modules/.bin/firebase deploy --project fasherge --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  standard-workflow:
    jobs:
      - test:
          name: test
      - deploy:
          name: deploy
          env: PRODUCTION
          requires:
            - test
          filters:
            branches:
              only: master
